os: linux
dist: xenial

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/601eba4ae3738ceb2406
    on_success: change
    on_failure: always
    on_start: never

addons:
  apt:
    update: true

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -q -r dev-requirements.txt
  - pip install -q -r requirements.txt

script:
  - flake8 docs/conf.py examples pymanopt setup.py tests
  - >
    nose2 tests
    --verbose
    --with-coverage

after_success:
  - coveralls
  - >
    PYTHONPATH=. sphinx-build
    -b html
    -D version=latest
    -D release=latest
    docs
    website/docs

deploy:
  - provider: pypi
    username: $TWINE_USER
    password: $TWINE_PW
    on:
      repo: pymanopt/pymanopt
      tags: true
    distributions: "sdist bdist_wheel"
    skip_existing: true
  - provider: pages
    skip_cleanup: true
    token: $GITHUB_PAGES_TOKEN
    keep_history: true
    repo: pymanopt/pymanopt.github.io
    target_branch: master
    fqdn: www.pymanopt.org
    project_name: pymanopt
    on:
      condition: >
                 $TRAVIS_PYTHON_VERSION = "3.7" &&
                 ($TRAVIS_BRANCH = "master" || -n $TRAVIS_TAG)
      repo: pymanopt/pymanopt
    local_dir: website
